// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port/clientside.proto

package protoport

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e25afba35f29a5, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateResponse struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e25afba35f29a5, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "port.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "port.CreateResponse")
}

func init() { proto.RegisterFile("port/clientside.proto", fileDescriptor_35e25afba35f29a5) }

var fileDescriptor_35e25afba35f29a5 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0xbf, 0x96, 0xb6, 0xf0, 0x9d, 0xd8, 0x21, 0x56, 0x28, 0x4e, 0x52, 0x51, 0x3a, 0xa5,
	0x60, 0x07, 0x07, 0x37, 0x05, 0x67, 0xa9, 0x9b, 0x5b, 0x6c, 0x6f, 0x08, 0xb4, 0x4d, 0x4d, 0x4e,
	0x7f, 0xbf, 0x24, 0x45, 0xa4, 0xdb, 0x9b, 0x87, 0x3c, 0xf7, 0xde, 0xc1, 0x72, 0x50, 0x9a, 0x8a,
	0xba, 0x95, 0xd8, 0x93, 0x91, 0x0d, 0xf2, 0x41, 0x2b, 0x52, 0x2c, 0xb0, 0x38, 0x2b, 0x61, 0x7e,
	0xd6, 0x28, 0x08, 0x2b, 0x7c, 0xbe, 0xd0, 0x10, 0x8b, 0xc1, 0x97, 0x4d, 0xea, 0xad, 0xbd, 0xfc,
	0xbf, 0xf2, 0x65, 0xc3, 0x18, 0x04, 0xbd, 0xe8, 0x30, 0xf5, 0x1d, 0x71, 0x39, 0xdb, 0x41, 0xfc,
	0x95, 0xcc, 0xa0, 0x7a, 0x83, 0x2c, 0x81, 0x90, 0x14, 0x89, 0xd6, 0x89, 0x61, 0x35, 0x3e, 0xf6,
	0x17, 0x98, 0x5d, 0x95, 0xa6, 0x1b, 0xea, 0xb7, 0xac, 0x91, 0x1d, 0x20, 0x1a, 0x35, 0xb6, 0xe0,
	0xb6, 0x9c, 0x4f, 0x9a, 0x57, 0xc9, 0x14, 0x8e, 0x93, 0xb3, 0xbf, 0xdc, 0x3b, 0x6d, 0xef, 0x9b,
	0xdf, 0xfa, 0x86, 0x34, 0x8a, 0x8e, 0xd7, 0xaa, 0x2b, 0xec, 0xff, 0xa3, 0xbb, 0xc6, 0xa6, 0x47,
	0xe4, 0x62, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x3f, 0xf5, 0x27, 0xf1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	Create(ctx context.Context, opts ...grpc.CallOption) (PortService_CreateClient, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) Create(ctx context.Context, opts ...grpc.CallOption) (PortService_CreateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PortService_serviceDesc.Streams[0], "/port.PortService/Create", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceCreateClient{stream}
	return x, nil
}

type PortService_CreateClient interface {
	Send(*CreateRequest) error
	CloseAndRecv() (*CreateResponse, error)
	grpc.ClientStream
}

type portServiceCreateClient struct {
	grpc.ClientStream
}

func (x *portServiceCreateClient) Send(m *CreateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceCreateClient) CloseAndRecv() (*CreateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	Create(PortService_CreateServer) error
}

// UnimplementedPortServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (*UnimplementedPortServiceServer) Create(srv PortService_CreateServer) error {
	return status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).Create(&portServiceCreateServer{stream})
}

type PortService_CreateServer interface {
	SendAndClose(*CreateResponse) error
	Recv() (*CreateRequest, error)
	grpc.ServerStream
}

type portServiceCreateServer struct {
	grpc.ServerStream
}

func (x *portServiceCreateServer) SendAndClose(m *CreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceCreateServer) Recv() (*CreateRequest, error) {
	m := new(CreateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "port.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _PortService_Create_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "port/clientside.proto",
}
